name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run base test
        run: npm run test

      - name: Run PGP test
        run: npm run test:pgp

      - name: Run S/MIME test
        env:
          SMIME_CERT_PEM: ${{ secrets.SMIME_CERT_PEM }}
          SMIME_KEY_PEM: ${{ secrets.SMIME_KEY_PEM }}
        run: npm run test:smime
